# Generated by Django 3.1.1 on 2021-02-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('list_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('list_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shirts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('list_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('list_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_shirts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('list_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
