# Generated by Django 3.1.1 on 2021-02-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0002_auto_20210220_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jean',
            name='list_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='polo',
            name='list_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shirts',
            name='list_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='suites',
            name='list_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='t_shirts',
            name='list_date',
            field=models.DateField(),
        ),
    ]
